POST http://localhost:3001/register
Content-Type:application/json

{
    "username":"jyothisha",
    "password":"jyo456"
}

###
POST http://localhost:3001/login
Content-Type:application/json
Authorization: BEARER SECRET_TOKEN
{
    "username":"jyo",
    "password":"jyo456"
}


###
GET http://localhost:3001/
Authorization: BEARER SECRET_TOKEN

###
POST http://localhost:3001/courier/
Content-Type: application/json
Authorization: BEARER SECRET_TOKEN

{
    "TrackingNumber": "TPK123456789",
    "SenderName": "Rajesh",
    "SenderAddress": "123 Main St, Anytown",
    "RecipientName":"Priya Patel",
    "RecipientAddress": "456 Elm St, Othercity",
    "PackageDescription": "Small Box",
    "Status": "In Transit",
    "LastUpdated": "2024-02-21 10:30:00"
}

###
PUT http://localhost:3001/courier/:courierId
Content-Type: application/json
Authorization: BEARER SECRET_TOKEN


{
    "TrackingNumber": "TFK123456789",
    "SenderName": "Rajesh R Nandi U",
    "SenderAddress": "124 Main St, Anytown",
    "RecipientName":"Priya Patel",
    "RecipientAddress": "456 Elm St, Othercity",
    "PackageDescription": "Small Box",
    "Status": "In Transit",
    "LastUpdated": "2024-02-21 10:30:00"
}

###
DELETE http://localhost:3001/courier/:courierId
Authorization: BEARER SECRET_TOKEN
